<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="microsoft.net.test.sdk" Version="18.10.0" />
    <PackageReference Include="nsubstitute" Version="6.2.0" />
    <PackageReference Include="nunit" Version="4.6.1" />
    <PackageReference Include="nunit3testadapter" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TestDummyProcess\TestDummyProcess.csproj" />
    <ProjectReference Include="..\DiskQueue\DiskQueue.csproj" />
  </ItemGroup>

</Project>
